### PR TITLE
Blog app: add authorization rules

### PR DESCRIPTION
**Pull request by RiyaBulia12**
## [Project Description](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_add_authorization.md)
In this project, limit the access to web app resources based on authorization rules.

### General requirements
- [No linter errors](https://github.com/microverseinc/linters-config).
- Correct flow [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Follow list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).
- New [README](https://github.com/microverseinc/readme-template)

### Steps Followed                    
- Installed CanCanCan.
- Added a `role` column to the users' table. 
- Added a feature for users to delete a post if it is theirs or if they have an admin role 
    - Implemented the post-deleting functionality. Added the "Delete" button to the view and make sure that only authorized users can see it.
- Added a feature for users to delete a comment if it is theirs or if they have an admin role (
    - Implemented the comment-deleting functionality. Added the "Delete" button to the view and make sure that only authorized users can see it.

### Collaborators:
- @Paul-js-hub 
- @summyalena 
- @RiyaBulia12

### CODE REVIEW

**Review by andersonlebon — CHANGES_REQUESTED** [review]
### Hello team
Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
# Required Changes ♻️

- [x] Kindly remove the template logo in your README. Optionally, you can replace with your own logo if you have one.
Screenshot from 2022-12-15 12-16-20


- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Comment by RiyaBulia12** [comment]
> ### Hello team
> Good job so far! I know you have worked hard on making this milestone But There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> almost-there [ almost-there ](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif) [ ](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
> 
> ## To highlight 🍾
> * All linters are passing ✔️
> * Good commit history ✔️
> * Your design looks good 💯 ✔️
> * Good PR description ✔️
> 
> # Required Changes ♻️
> * [x]  Kindly remove the template logo in your README. Optionally, you can replace with your own logo if you have one.
>   Screenshot from 2022-12-15 12-16-20
> * [ ]  Kindly check comments under the review.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by RiyaBulia12** [comment]
I closed the PR by mistake. Reopened it again

**Review by tresorsawasawa — APPROVED** [review]
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @RiyaBulia12 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
